version: "3.8"

services:
  idp-crawl-frontend-app:
    image: idp-crawl-frontend-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idp-crawl-frontend-app
    restart: always
    networks:
      - main_network
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./.env

networks:
  main_network:
    name: main_network