version: "3.8"

services:
  idp-crawl-backend-mongo-db:
    image: mongo:6.0.7
    container_name: idp-crawl-backend-mongo-db
    restart: always
    networks:
      - idp-crawl-backend-net
    env_file:
      - ./.env
    volumes:
      - /idp-crawl/db_data:/data/db

  idp-crawl-backend-api:
    image: idp-crawl-backend-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idp-crawl-backend-api
    restart: always
    networks:
      - idp-crawl-backend-net
      - main_network
    depends_on:
      - idp-crawl-backend-mongo-db
    env_file:
      - ./.env
    volumes:
      - /cryp_bot/logs:/home/node/app/logs

networks:
  idp-crawl-backend-net:
    name: idp-crawl-backend-net
    driver: bridge
  main_network:
    name: main_network