name: update-server
run-name: Updated by ${{ github.actor }}.
on: 
  push:
    branches:    
      - main
jobs:
  update-docker-container:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ vars.BACKEND_ENV_FILE }}" > ./backend/.env
      - run: echo "${{ vars.FRONTEND_ENV_FILE }}" > ./frontend/.env
      - run: cd backend && docker compose up -d --build
      - run: cd frontend && docker compose up -d --build